steps:
  - name: 'ubuntu'
    entrypoint: 'bash'
    args: ['-c', 'mkdir -p /workspace/input/chart']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://isv-ci-staging/${_CHART_NAME}', '/workspace/input/chart/']

  - name: 'ubuntu'
    entrypoint: 'bash'
    args: ['-c', 'ls /workspace/input/chart']

  - name: 'gcr.io/fe-rabbit-mq-tile-ci/nsie-test'
    env:
      - 'CLUSTER_NAME=${_CLUSTER_NAME}'
      - 'PKS_API_ENDPOINT=${_PKS_API_ENDPOINT}'
      - 'PKS_USERNAME=${_PKS_USERNAME}'
      - 'PKS_PASSWORD=${_PKS_PASSWORD}'
      - 'CHART_DIRECTORY=/workspace/input/chart'
