#!/usr/bin/env bash

set -xeo pipefail

PKS_API=$(cat /input/pks-environment.json | jq -r ".pks_api.url")
PKS_USERNAME=$(cat /input/pks-environment.json | jq -r ".pks_api.uaa_admin_user")
PKS_PASSWORD=$(cat /input/pks-environment.json | jq -r ".pks_api.uaa_admin_password")

pks login -a "${PKS_API}" -u "${PKS_USERNAME}" -p "${PKS_PASSWORD}" -k

PKS_CLUSTER=$(pks clusters --json | jq -r '.[0].name')
pks get-credentials "${PKS_CLUSTER}"