#!/usr/bin/env bash

set -xeo pipefail

cd /tmp
pivnet login --api-token "${PIVNET_TOKEN}"
pivnet download-product-files \
  --product-slug=pivotal-container-service \
  --release-version='1.6.1' \
  --glob pks-linux-*
mv pks-linux* /usr/local/bin/pks
chmod +x /usr/local/bin/pks