#!/usr/bin/env bash

set -xeo pipefail

creator_sak_path=${1}
account_prefix=${2}

export BBL_IAAS=gcp
export BBL_GCP_SERVICE_ACCOUNT_KEY="$(cat "${creator_sak_path}")"

leftovers --filter "${account_prefix}" --no-confirm