#!/usr/bin/env bash

# The KUBECONFIG environment variable will affect the output of this script

if [[ -z "${K8S_SERVER}" ]] ; then
    >&2 echo "K8S_SERVER must be defined"
    exit 1
fi

if [[ -z "${K8S_USER_TOKEN}" ]] ; then
    >&2 echo "K8S_USER_TOKEN must be defined"
    exit 1
fi

if [[ -z "${K8S_CLUSTER}" ]] ; then
    >&2 echo "K8S_CLUSTER must be defined"
    exit 1
fi

K8S_USER_NAME=isv-ci-test-user

kubectl config set-credentials "${K8S_USER_NAME}" --token="${K8S_USER_TOKEN}"

echo "${K8S_SERVER_CA}" | base64 --decode > /tmp/$$_ca.cert
kubectl config set-cluster "${K8S_CLUSTER}" --server="${K8S_SERVER}" --certificate-authority=/tmp/$$_ca.cert --embed-certs=true
rm /tmp/$$_ca.cert

kubectl config set-context "${K8S_CLUSTER}" --user="${K8S_USER_NAME}" --cluster="${K8S_CLUSTER}" --namespace=default
kubectl config use-context "${K8S_CLUSTER}"
