product-name: cf
product-properties:
  .properties.tcp_routing:
    value: enable
  .properties.tcp_routing.enable.reservable_ports:
    value: 1024-1123
resource-config:
  tcp_router:
    instances: 1
    elb_names:
    - tcp:ELB_NAME
