steps:
  - name: 'cfplatformeng/test-mysql-standalone:latest'
    env:
      - 'K8S_CLUSTER=${_K8S_CLUSTER}'
      - 'K8S_SERVER=${_K8S_SERVER}'
      - 'K8S_SERVER_CA=${_K8S_SERVER_CA}'
      - 'K8S_USER_TOKEN=${_K8S_USER_TOKEN}'
