---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfplatformeng/dcind-golang-test-image

inputs:
  - name: source

params:
  CI: true

run:
  path: /bin/sh

  args:
    - -exc
    - |
      source /docker-lib.sh
      start_docker

      cd source/base-image
      make test
