---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: amidos/dcind

inputs:
  - name: source

params:
  CI: true

run:
  path: /bin/bash

  args:
    - -exc
    - |
      source /docker-lib.sh
      start_docker
      cd source/base-image
      make test
