// Code generated by counterfeiter. DO NOT EDIT.
package pivnetfakes

import (
	io "io"
	sync "sync"

	pivnet "github.com/cf-platform-eng/isv-ci-toolkit/marman/pivnet"
	pivneta "github.com/pivotal-cf/go-pivnet"
	download "github.com/pivotal-cf/go-pivnet/download"
)

type FakeClient struct {
	AcceptEULAStub        func(string, int) error
	acceptEULAMutex       sync.RWMutex
	acceptEULAArgsForCall []struct {
		arg1 string
		arg2 int
	}
	acceptEULAReturns struct {
		result1 error
	}
	acceptEULAReturnsOnCall map[int]struct {
		result1 error
	}
	DownloadProductFileStub        func(*download.FileInfo, string, int, int, io.Writer) error
	downloadProductFileMutex       sync.RWMutex
	downloadProductFileArgsForCall []struct {
		arg1 *download.FileInfo
		arg2 string
		arg3 int
		arg4 int
		arg5 io.Writer
	}
	downloadProductFileReturns struct {
		result1 error
	}
	downloadProductFileReturnsOnCall map[int]struct {
		result1 error
	}
	ListFilesForReleaseStub        func(string, int) ([]pivneta.ProductFile, error)
	listFilesForReleaseMutex       sync.RWMutex
	listFilesForReleaseArgsForCall []struct {
		arg1 string
		arg2 int
	}
	listFilesForReleaseReturns struct {
		result1 []pivneta.ProductFile
		result2 error
	}
	listFilesForReleaseReturnsOnCall map[int]struct {
		result1 []pivneta.ProductFile
		result2 error
	}
	ListReleasesStub        func(string) ([]pivneta.Release, error)
	listReleasesMutex       sync.RWMutex
	listReleasesArgsForCall []struct {
		arg1 string
	}
	listReleasesReturns struct {
		result1 []pivneta.Release
		result2 error
	}
	listReleasesReturnsOnCall map[int]struct {
		result1 []pivneta.Release
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClient) AcceptEULA(arg1 string, arg2 int) error {
	fake.acceptEULAMutex.Lock()
	ret, specificReturn := fake.acceptEULAReturnsOnCall[len(fake.acceptEULAArgsForCall)]
	fake.acceptEULAArgsForCall = append(fake.acceptEULAArgsForCall, struct {
		arg1 string
		arg2 int
	}{arg1, arg2})
	fake.recordInvocation("AcceptEULA", []interface{}{arg1, arg2})
	fake.acceptEULAMutex.Unlock()
	if fake.AcceptEULAStub != nil {
		return fake.AcceptEULAStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.acceptEULAReturns
	return fakeReturns.result1
}

func (fake *FakeClient) AcceptEULACallCount() int {
	fake.acceptEULAMutex.RLock()
	defer fake.acceptEULAMutex.RUnlock()
	return len(fake.acceptEULAArgsForCall)
}

func (fake *FakeClient) AcceptEULACalls(stub func(string, int) error) {
	fake.acceptEULAMutex.Lock()
	defer fake.acceptEULAMutex.Unlock()
	fake.AcceptEULAStub = stub
}

func (fake *FakeClient) AcceptEULAArgsForCall(i int) (string, int) {
	fake.acceptEULAMutex.RLock()
	defer fake.acceptEULAMutex.RUnlock()
	argsForCall := fake.acceptEULAArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClient) AcceptEULAReturns(result1 error) {
	fake.acceptEULAMutex.Lock()
	defer fake.acceptEULAMutex.Unlock()
	fake.AcceptEULAStub = nil
	fake.acceptEULAReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) AcceptEULAReturnsOnCall(i int, result1 error) {
	fake.acceptEULAMutex.Lock()
	defer fake.acceptEULAMutex.Unlock()
	fake.AcceptEULAStub = nil
	if fake.acceptEULAReturnsOnCall == nil {
		fake.acceptEULAReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.acceptEULAReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) DownloadProductFile(arg1 *download.FileInfo, arg2 string, arg3 int, arg4 int, arg5 io.Writer) error {
	fake.downloadProductFileMutex.Lock()
	ret, specificReturn := fake.downloadProductFileReturnsOnCall[len(fake.downloadProductFileArgsForCall)]
	fake.downloadProductFileArgsForCall = append(fake.downloadProductFileArgsForCall, struct {
		arg1 *download.FileInfo
		arg2 string
		arg3 int
		arg4 int
		arg5 io.Writer
	}{arg1, arg2, arg3, arg4, arg5})
	fake.recordInvocation("DownloadProductFile", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.downloadProductFileMutex.Unlock()
	if fake.DownloadProductFileStub != nil {
		return fake.DownloadProductFileStub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.downloadProductFileReturns
	return fakeReturns.result1
}

func (fake *FakeClient) DownloadProductFileCallCount() int {
	fake.downloadProductFileMutex.RLock()
	defer fake.downloadProductFileMutex.RUnlock()
	return len(fake.downloadProductFileArgsForCall)
}

func (fake *FakeClient) DownloadProductFileCalls(stub func(*download.FileInfo, string, int, int, io.Writer) error) {
	fake.downloadProductFileMutex.Lock()
	defer fake.downloadProductFileMutex.Unlock()
	fake.DownloadProductFileStub = stub
}

func (fake *FakeClient) DownloadProductFileArgsForCall(i int) (*download.FileInfo, string, int, int, io.Writer) {
	fake.downloadProductFileMutex.RLock()
	defer fake.downloadProductFileMutex.RUnlock()
	argsForCall := fake.downloadProductFileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeClient) DownloadProductFileReturns(result1 error) {
	fake.downloadProductFileMutex.Lock()
	defer fake.downloadProductFileMutex.Unlock()
	fake.DownloadProductFileStub = nil
	fake.downloadProductFileReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) DownloadProductFileReturnsOnCall(i int, result1 error) {
	fake.downloadProductFileMutex.Lock()
	defer fake.downloadProductFileMutex.Unlock()
	fake.DownloadProductFileStub = nil
	if fake.downloadProductFileReturnsOnCall == nil {
		fake.downloadProductFileReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.downloadProductFileReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) ListFilesForRelease(arg1 string, arg2 int) ([]pivneta.ProductFile, error) {
	fake.listFilesForReleaseMutex.Lock()
	ret, specificReturn := fake.listFilesForReleaseReturnsOnCall[len(fake.listFilesForReleaseArgsForCall)]
	fake.listFilesForReleaseArgsForCall = append(fake.listFilesForReleaseArgsForCall, struct {
		arg1 string
		arg2 int
	}{arg1, arg2})
	fake.recordInvocation("ListFilesForRelease", []interface{}{arg1, arg2})
	fake.listFilesForReleaseMutex.Unlock()
	if fake.ListFilesForReleaseStub != nil {
		return fake.ListFilesForReleaseStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.listFilesForReleaseReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) ListFilesForReleaseCallCount() int {
	fake.listFilesForReleaseMutex.RLock()
	defer fake.listFilesForReleaseMutex.RUnlock()
	return len(fake.listFilesForReleaseArgsForCall)
}

func (fake *FakeClient) ListFilesForReleaseCalls(stub func(string, int) ([]pivneta.ProductFile, error)) {
	fake.listFilesForReleaseMutex.Lock()
	defer fake.listFilesForReleaseMutex.Unlock()
	fake.ListFilesForReleaseStub = stub
}

func (fake *FakeClient) ListFilesForReleaseArgsForCall(i int) (string, int) {
	fake.listFilesForReleaseMutex.RLock()
	defer fake.listFilesForReleaseMutex.RUnlock()
	argsForCall := fake.listFilesForReleaseArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClient) ListFilesForReleaseReturns(result1 []pivneta.ProductFile, result2 error) {
	fake.listFilesForReleaseMutex.Lock()
	defer fake.listFilesForReleaseMutex.Unlock()
	fake.ListFilesForReleaseStub = nil
	fake.listFilesForReleaseReturns = struct {
		result1 []pivneta.ProductFile
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListFilesForReleaseReturnsOnCall(i int, result1 []pivneta.ProductFile, result2 error) {
	fake.listFilesForReleaseMutex.Lock()
	defer fake.listFilesForReleaseMutex.Unlock()
	fake.ListFilesForReleaseStub = nil
	if fake.listFilesForReleaseReturnsOnCall == nil {
		fake.listFilesForReleaseReturnsOnCall = make(map[int]struct {
			result1 []pivneta.ProductFile
			result2 error
		})
	}
	fake.listFilesForReleaseReturnsOnCall[i] = struct {
		result1 []pivneta.ProductFile
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListReleases(arg1 string) ([]pivneta.Release, error) {
	fake.listReleasesMutex.Lock()
	ret, specificReturn := fake.listReleasesReturnsOnCall[len(fake.listReleasesArgsForCall)]
	fake.listReleasesArgsForCall = append(fake.listReleasesArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("ListReleases", []interface{}{arg1})
	fake.listReleasesMutex.Unlock()
	if fake.ListReleasesStub != nil {
		return fake.ListReleasesStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.listReleasesReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) ListReleasesCallCount() int {
	fake.listReleasesMutex.RLock()
	defer fake.listReleasesMutex.RUnlock()
	return len(fake.listReleasesArgsForCall)
}

func (fake *FakeClient) ListReleasesCalls(stub func(string) ([]pivneta.Release, error)) {
	fake.listReleasesMutex.Lock()
	defer fake.listReleasesMutex.Unlock()
	fake.ListReleasesStub = stub
}

func (fake *FakeClient) ListReleasesArgsForCall(i int) string {
	fake.listReleasesMutex.RLock()
	defer fake.listReleasesMutex.RUnlock()
	argsForCall := fake.listReleasesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClient) ListReleasesReturns(result1 []pivneta.Release, result2 error) {
	fake.listReleasesMutex.Lock()
	defer fake.listReleasesMutex.Unlock()
	fake.ListReleasesStub = nil
	fake.listReleasesReturns = struct {
		result1 []pivneta.Release
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListReleasesReturnsOnCall(i int, result1 []pivneta.Release, result2 error) {
	fake.listReleasesMutex.Lock()
	defer fake.listReleasesMutex.Unlock()
	fake.ListReleasesStub = nil
	if fake.listReleasesReturnsOnCall == nil {
		fake.listReleasesReturnsOnCall = make(map[int]struct {
			result1 []pivneta.Release
			result2 error
		})
	}
	fake.listReleasesReturnsOnCall[i] = struct {
		result1 []pivneta.Release
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.acceptEULAMutex.RLock()
	defer fake.acceptEULAMutex.RUnlock()
	fake.downloadProductFileMutex.RLock()
	defer fake.downloadProductFileMutex.RUnlock()
	fake.listFilesForReleaseMutex.RLock()
	defer fake.listFilesForReleaseMutex.RUnlock()
	fake.listReleasesMutex.RLock()
	defer fake.listReleasesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pivnet.Client = new(FakeClient)
