resources:
  - name: ci-source
    type: git
    source:
      uri: ((github.org_url))/isv-dashboard-ci.git
      username: ((github.username))
      password: ((github.broadcom_github_personal_access_token))

  - name: oci-build-task
    type: registry-image
    check_every: 4h
    icon: oci
    source:
      repository: ((artifactory.registry_mirror))/concourse/oci-build-task
      tag: 0.11.1
      username: ((artifactory.production_username))
      password: ((artifactory.production_password))

  - name: base-image-source
    type: git
    source:
      paths:
        - base-image/*
        - base-image/**/*
      uri: git@github.com:cf-platform-eng/isv-ci-toolkit.git
      private_key: ((github.private_key))

  - name: base-image
    type: registry-image
    source:
      repository: tas-ecosystem-docker-prod-local.usw1.packages.broadcom.com/tanzu-isv-engineering/base-image
      username: ((artifactory.production_username))
      password: ((artifactory.production_password))
      tag: 0.0.53

  - name: om-image
    type: registry-image
    source:
      repository: tas-ecosystem-docker-prod-local.usw1.packages.broadcom.com/tanzu-isv-engineering/om-image
      username: ((artifactory.production_username))
      password: ((artifactory.production_password))
      tag: 7.7.0

  - name: enable-apps-manager-source
    type: git
    source:
      paths:
        - tasks/enable-apps-manager/*
      uri: git@github.com:cf-platform-eng/isv-ci-toolkit.git
      private_key: ((github.private_key))

  - name: enable-apps-manager
    type: registry-image
    source:
      repository: tas-ecosystem-docker-prod-local.usw1.packages.broadcom.com/tanzu-isv-engineering/enable-apps-manager
      username: ((artifactory.production_username))
      password: ((artifactory.production_password))
      tag: latest

  - name: enable-bosh-post-deploy-scripts-source
    type: git
    source:
      paths:
        - tasks/enable-bosh-post-deploy-scripts/Dockerfile
      uri: git@github.com:cf-platform-eng/isv-ci-toolkit.git
      private_key: ((github.private_key))

  - name: enable-bosh-post-deploy-scripts
    type: registry-image
    source:
      repository: tas-ecosystem-docker-prod-local.usw1.packages.broadcom.com/tanzu-isv-engineering/enable-bosh-post-deploy-scripts
      username: ((artifactory.production_username))
      password: ((artifactory.production_password))
      tag: latest

  - name: enable-tcp-routing-source
    type: git
    source:
      paths:
        - tasks/enable-tcp-routing/*
      uri: git@github.com:cf-platform-eng/isv-ci-toolkit.git
      private_key: ((github.private_key))

  - name: enable-tcp-routing
    type: docker-image
    source:
      repository: us-west1-docker.pkg.dev/isv-tile-partners/tanzu-isv-engineering/enable-tcp-routing
      username: _json_key
      password: ((gcp_artifact_registry.service_account_key))
      tag: latest

  - name: toolkit-source
    type: git
    source:
      uri: git@github.com:cf-platform-eng/isv-ci-toolkit.git
      private_key: ((github.private_key))

  - name: toolkit-tools-source
    type: git
    source:
      paths:
        - tools/*
      uri: git@github.com:cf-platform-eng/isv-ci-toolkit.git
      private_key: ((github.private_key))

  - name: toolkit-image
    type: docker-image
    source:
      repository: us-west1-docker.pkg.dev/isv-tile-partners/tanzu-isv-engineering/isv-ci-toolkit
      username: _json_key
      password: ((gcp_artifact_registry.service_account_key))
      tag: latest

  - name: toolkit-version
    type: semver
    source:
      driver: git
      uri: ((github.org_url))/isv-ci-versions.git
      branch: main
      file: isv-ci-toolkit
      username: ((github.username))
      password: ((github.broadcom_github_personal_access_token))

  - name: base-image-version
    type: semver
    source:
      driver: git
      uri: ((github.org_url))/isv-ci-versions.git
      branch: main
      file: base-image
      username: ((github.username))
      password: ((github.broadcom_github_personal_access_token))

  - name: alpine
    type: registry-image
    icon: docker
    source:
      repository: mirror.gcr.io/alpine
      tag: 3
      username: _json_key
      password: ((gcp_artifact_registry.service_account_key))

  - name: bosh
    type: github-release
    source:
        owner: cloudfoundry
        repository: bosh-cli
        access_token: ((github.access_token))

  - name: bosh-docker-image
    type: docker-image
    source:
      repository: us-west1-docker.pkg.dev/isv-tile-partners/tanzu-isv-engineering/bosh
      username: _json_key
      password: ((gcp_artifact_registry.service_account_key))
      tag: latest

  - name: cf
    type: github-release
    source:
        owner: cloudfoundry
        repository: cli
        access_token: ((github.access_token))

  - name: cf-image
    type: registry-image
    source:
      repository: tas-ecosystem-docker-prod-local.usw1.packages.broadcom.com/tanzu-isv-engineering/cf
      username: ((artifactory.production_username))
      password: ((artifactory.production_password))
      tag: latest

  - name: leftovers
    type: github-release
    source:
        owner: genevieve
        repository: leftovers
        access_token: ((github.access_token))

  - name: leftovers-docker-image
    type: docker-image
    source:
      repository: us-west1-docker.pkg.dev/isv-tile-partners/partner-engineering/leftovers
      username: _json_key
      password: ((gcp_artifact_registry.service_account_key))
      tag: latest

  - name: om
    type: github-release
    source:
        owner: pivotal-cf
        repository: om
        access_token: ((github.access_token))

  - name: om-docker-image
    type: docker-image
    source:
      repository: us-west1-docker.pkg.dev/isv-tile-partners/tanzu-isv-engineering/om
      username: _json_key
      password: ((gcp_artifact_registry.service_account_key))
      tag: latest

  - name: pivnet
    type: github-release
    source:
        owner: pivotal-cf
        repository: pivnet-cli
        access_token: ((github.access_token))

  - name: uaa
    type: github-release
    source:
        owner: cloudfoundry-incubator
        repository: uaa-cli
        access_token: ((github.access_token))

  - name: pivnet-docker-image
    type: docker-image
    source:
      repository: us-west1-docker.pkg.dev/isv-tile-partners/tanzu-isv-engineering/pivnet
      username: _json_key
      password: ((gcp_artifact_registry.service_account_key))
      tag: latest

  - name: uaa-docker-image
    type: docker-image
    source:
      repository: us-west1-docker.pkg.dev/isv-tile-partners/tanzu-isv-engineering/uaa
      username: _json_key
      password: ((gcp_artifact_registry.service_account_key))
      tag: latest

  - name: ubuntu-image
    type: registry-image
    icon: oci
    source:
      repository: ((artifactory.registry_mirror))/ubuntu
      tag: 20.04
      username: ((artifactory.production_username))
      password: ((artifactory.production_password))

  - name: mrlog-image
    type: registry-image
    icon: oci
    source:
      repository: tas-ecosystem-docker-prod-local.usw1.packages.broadcom.com/tanzu-isv-engineering/mrlog
      tag: 0.2.9
      username: ((artifactory.production_username))
      password: ((artifactory.production_password))

  - name: needs-image
    type: registry-image
    icon: oci
    source:
      repository: tas-ecosystem-docker-prod-local.usw1.packages.broadcom.com/tanzu-isv-engineering/needs
      tag: 0.12.12
      username: ((artifactory.production_username))
      password: ((artifactory.production_password))

jobs:
  - name: build-base-image
    serial_groups: [base-image-version]
    plan:
      - in_parallel:
        - get: base-image-source
          trigger: true
        - get: ubuntu-image
          params:
            format: oci
        - get: mrlog-image
          params:
            format: oci
        - get: needs-image
          params:
            format: oci
      - get: oci-build-task
        attempts: 3
      - get: base-image-version
        params:
          bump: patch
      - task: build-oci
        privileged: true
        image: oci-build-task
        config:
          platform: linux
          inputs:
            - name: base-image-source
            - name: ubuntu-image
            - name: mrlog-image
            - name: needs-image
          outputs:
            - name: image
          params:
            CONTEXT: base-image-source/base-image
            DOCKERFILE: base-image-source/base-image/Dockerfile
            IMAGE_ARG_ubuntu_image: ubuntu-image/image.tar
            IMAGE_ARG_mrlog_image: mrlog-image/image.tar
            IMAGE_ARG_needs_image: needs-image/image.tar
          run:
            path: build
        output_mapping:
          image: base-image-out
      - file: base-image-version/version
        load_var: image_version
      - put: base-image
        inputs: detect
        attempts: 3
        params:
          image: base-image-out/image.tar
          version: ((.:image_version))
          bump_aliases: true
      - put: base-image-version
        inputs: detect
        params:
          file: base-image-version/version

  - name: build-enable-apps-manager
    plan:
      - in_parallel:
        - get: source
          resource: enable-apps-manager-source
          trigger: true
        - get: base-image
          params:
            format: oci
        - get: om-image
          params:
            format: oci
      - task: build-oci
        privileged: true
        image: oci-build-task
        config:
          platform: linux
          inputs:
            - name: base-image
            - name: om-image
          outputs:
            - name: image
          params:
            CONTEXT: source/tasks/enable-apps-manager
            DOCKERFILE: source/tasks/enable-apps-manager/Dockerfile
            IMAGE_ARG_base_image: base-image/image.tar
            IMAGE_ARG_om_image: om-image/image.tar
          run:
            path: build
        output_mapping:
          image: enable-apps-manager-image-out
      - put: enable-apps-manager
        inputs: detect
        params:
          image: enable-apps-manager-image-out/image.tar
          bump_aliases: true

  - name: build-enable-bosh-post-deploy-scripts
    plan:
      - in_parallel:
          - get: source
            resource: enable-bosh-post-deploy-scripts-source
            trigger: true
          - get: base-image
            params:
              format: oci
          - get: om-image
            params:
              format: oci
      - task: build-oci
        privileged: true
        image: oci-build-task
        config:
          platform: linux
          inputs:
            - name: base-image
            - name: om-image
          outputs:
            - name: image
          params:
            CONTEXT: source/tasks/enable-bosh-post-deploy-scripts
            DOCKERFILE: source/tasks/enable-bosh-post-deploy-scripts/Dockerfile
            IMAGE_ARG_base_image: base-image/image.tar
            IMAGE_ARG_om_image: om-image/image.tar
          run:
            path: build
        output_mapping:
          image: enable-bosh-post-deploy-scripts-image-out
      - put: enable-bosh-post-deploy-scripts
        inputs: detect
        params:
          image: enable-bosh-post-deploy-scripts-image-out/image.tar
          bump_aliases: true

  - name: build-enable-tcp-routing
    plan:
      - in_parallel:
          - get: source
            resource: enable-tcp-routing-source
            trigger: true
          - get: base-image
            params:
              format: oci
          - get: om-image
            params:
              format: oci
          - get: cf-image
            params:
              format: oci
      - task: build-oci
        privileged: true
        image: oci-build-task
        config:
          platform: linux
          inputs:
            - name: base-image
            - name: om-image
            - name: cf-image
          outputs:
            - name: image
          params:
            CONTEXT: source/tasks/enable-tcp-routing
            DOCKERFILE: source/tasks/enable-tcp-routing/Dockerfile
            IMAGE_ARG_base_image: base-image/image.tar
            IMAGE_ARG_om_image: om-image/image.tar
            IMAGE_ARG_cf_image: cf-image/image.tar
          run:
            path: build
        output_mapping:
          image: enable-tcp-routing-image-out
      - put: enable-tcp-routing
        inputs: detect
        params:
          image: enable-tcp-routing-image-out/image.tar
          bump_aliases: true

  - name: build-toolkit-image
    serial_groups: [toolkit-version]
    plan:
      - in_parallel:
        - get: toolkit-tools-source
          # passed:
          #   - test-toolkit
          trigger: true
        - get: toolkit-version
          params:
            bump: patch
      - put: toolkit-image
        inputs: detect
        params:
          build: toolkit-tools-source/tools
          cache: false
          tag_as_latest: false
          tag_file: toolkit-version/version
      - put: toolkit-version
        inputs: detect
        params:
          file: toolkit-version/version

  - name: build-bosh-image
    plan:
      - in_parallel:
        - get: alpine
        - get: toolkit-source
        - get: ci-source
        - get: bosh
          trigger: true
      - task: make-build-args-file
        image: alpine
        file: ci-source/tasks/build-docker-args.yml
        input_mapping: { src: bosh }
        params: { ENV_VAR: BOSH_CLI_VER }
      - put: bosh-docker-image
        inputs: detect
        params:
          build: toolkit-source/images
          build_args_file: build-args/args.json
          dockerfile: toolkit-source/images/Dockerfile.bosh
          tag_as_latest: false
          tag_file: bosh/version
          cache: false

  - name: build-cf-image
    plan:
      - in_parallel:
        - get: alpine
        - get: toolkit-source
        - get: ci-source        
        - get: cf
          trigger: true
      - task: make-build-args-file
        image: alpine
        file: ci-source/tasks/build-docker-args.yml
        input_mapping: { src: cf }
        params: { ENV_VAR: CF_CLI_VER }
      - put: cf-docker-image
        inputs: detect
        params:
          build: toolkit-source/images
          build_args_file: build-args/args.json
          dockerfile: toolkit-source/images/Dockerfile.cf
          tag_as_latest: false
          tag_file: cf/version
          cache: false

  - name: build-leftovers-image
    plan:
      - in_parallel:
        - get: alpine
        - get: toolkit-source
        - get: ci-source
        - get: leftovers
          trigger: true
      - task: make-build-args-file
        image: alpine
        file: ci-source/tasks/build-docker-args.yml
        input_mapping: { src: leftovers }
        params: { ENV_VAR: LEFTOVERS_VER }
      - put: leftovers-docker-image
        inputs: detect
        params:
          build: toolkit-source/images
          build_args_file: build-args/args.json
          dockerfile: toolkit-source/images/Dockerfile.leftovers
          tag_as_latest: false
          tag_file: leftovers/version
          cache: false

  - name: build-om-image
    plan:
      - in_parallel:
        - get: alpine
        - get: toolkit-source
        - get: ci-source
        - get: om
          trigger: true
      - task: make-build-args-file
        image: alpine
        file: ci-source/tasks/build-docker-args.yml
        input_mapping: { src: om }
        params: { ENV_VAR: OM_CLI_VER }
      - put: om-docker-image
        inputs: detect
        params:
          build: toolkit-source/images
          build_args_file: build-args/args.json
          dockerfile: toolkit-source/images/Dockerfile.om
          tag_as_latest: false
          tag_file: om/version
          cache: false

  - name: build-pivnet-image
    plan:
      - in_parallel:
        - get: alpine
        - get: ci-source
        - get: toolkit-source
        - get: pivnet
          trigger: true
      - task: make-build-args-file
        image: alpine
        file: ci-source/tasks/build-docker-args.yml
        input_mapping: { src: pivnet }
        params: { ENV_VAR: PIVNET_CLI_VER }
      - put: pivnet-docker-image
        inputs: detect
        params:
          build: toolkit-source/images
          build_args_file: build-args/args.json
          dockerfile: toolkit-source/images/Dockerfile.pivnet
          tag_as_latest: false
          tag_file: pivnet/version
          cache: false

  - name: build-uaa-image
    plan:
      - in_parallel:
        - get: alpine
        - get: toolkit-source
        - get: ci-source
        - get: uaa
          trigger: true
      - task: make-build-args-file
        image: alpine
        file: ci-source/tasks/build-docker-args.yml
        input_mapping: { src: uaa }
        params: { ENV_VAR: UAA_CLI_VER }
      - put: uaa-docker-image
        inputs: detect
        params:
          build: toolkit-source/images
          build_args_file: build-args/args.json
          dockerfile: toolkit-source/images/Dockerfile.uaa
          tag_as_latest: false
          tag_file: uaa/version
          cache: false

  - name: bump-toolkit-major-version
    serial_groups: [toolkit-version]
    plan:
      - put: toolkit-version
        inputs: detect
        params:
          bump: major

  - name: bump-toolkit-minor-version
    serial_groups: [toolkit-version]
    plan:
      - put: toolkit-version
        inputs: detect
        params:
          bump: minor

  - name: bump-base-image-major-version
    serial_groups: [base-image-version]
    plan:
      - put: base-image-version
        inputs: detect
        params:
          bump: major

  - name: bump-base-image-minor-version
    serial_groups: [base-image-version]
    plan:
      - put: base-image-version
        inputs: detect
        params:
          bump: minor
