steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/helm/charts']

  # This image built from this: https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/helm
  - name: 'gcr.io/fe-rabbit-mq-tile-ci/helm'
    entrypoint: 'helm'
    args: ['init', '--client-only']

  - name: 'ubuntu'
    entrypoint: 'bash'
    args: ['-c', 'mkdir -p /workspace/input/chart']

  - name: 'gcr.io/fe-rabbit-mq-tile-ci/helm'
    entrypoint: 'helm'
    args: ['package', '--destination', '/workspace/input/chart', '/workspace/charts/stable/mysql']

  - name: 'ubuntu'
    entrypoint: 'bash'
    args: ['-c', 'ls /workspace/input/chart']

  - name: 'gcr.io/fe-rabbit-mq-tile-ci/nsie-test'
    env:
      - 'CLUSTER_NAME=${_CLUSTER_NAME}'
      - 'PKS_API_ENDPOINT=${_PKS_API_ENDPOINT}'
      - 'PKS_USERNAME=${_PKS_USERNAME}'
      - 'PKS_PASSWORD=${_PKS_PASSWORD}'
      - 'CHART_DIRECTORY=/workspace/input/chart'
